import { EmailService } from "./EmailService";
export const emailService = new EmailService();
export { blogsService } from "./blogsService";
export { postsService } from "./postService";
export { usersService } from "./usersService";
export { bcryptService } from "./bcryptService";
export { authService } from "./authService";
export { devicesService } from "./devicesService";
export { commentsService } from "./commentsService";
