import { EmailService } from "./EmailService";
export const emailService = new EmailService();
export { blogService } from "./BlogService";
export { postService } from "./PostService";
export { userService } from "./UserService";
export { bcryptService } from "./BcryptService";
export { authService } from "./AuthService";
export { deviceService } from "./DeviceService";
export { commentService } from "./CommentService";
