import { EmailService } from "./EmailService";
export const emailService = new EmailService();
export { blogsService } from "./blogs-service";
export { postsService } from "./post-service";
export { usersService } from "./users-service";
export { bcryptService } from "./bcrypt-service";
export { authService } from "./auth-service";
export { devicesService } from "./devices-service";
export { commentsService } from "./comments-service";
